### PR TITLE
JSON Update

### PR DESCRIPTION
**Pull request by CorvusPrudens**
This PR incorporates the changes in #66 along with a few fixes and the addition of a few sensor components.

### CODE REVIEW

**Comment by beserge** [comment]
# Oopsy Full Test 1
## Daisy Pod
### json
- extra led3 and sw3
- nonexistent cvout1, gatein
- I think the pod and petal bugs were the same as we already fixed in pd. We should look over that review and fix those issues here too if they exist.

### templates/oopsy_pod.maxpat
- Tested pots, leds audio ins.
- Pot 1 sweeps lfo1. Causes led 1 to oscillate between red and blue.
- Pot 2 sweeps lfo 2. Causes led2 to oscillate between blue and purple at the same rate as led1.
- Audio passes through fine.
- This test misses: green led, encoder, switches
- We should update this template so it tests all of the functionality in one go, similar to the field test.

**Issues:**
- Led2 blue is stuck on.
- Template mentions rgb leds sweeping green -> red or something. These sweep red -> blue.

### Pot Test
Simply mapped pots to leds with @max 1 @min -1.
- Led 1 responded with red -> blue.
- Led 2 responded with purple -> blue. Seems like led2 may have blue stuck on.

**Issues:**
Again, these colors also don't agree with the comment that was left in here at some point.

Pasted image 20220329134221

### Encoder test
- Increment left led value with encoder turn.
- Set right led value with encoder click.

- Turning encoder left gets red. Back right gets off then blue
- Right led is purple. Pressing encoder turns it blue.

Encoder works!

Pasted image 20220329135201


### Switch test
Sw is rising edge bang by default. Need to use sw_pressed to get pressed behavior.

Both sw1 and sw2 work fine with bangs and pressed. The example patches sometimes use sw and when they should use sw_pressed.

Pasted image 20220329140018

## Daisy Field

###  templates/oopsy_field.maxpat

- All pots + pot leds work fine.
- All buttons + button leds work fine.
- Oled works fine.
- Sw1 and Sw2 interact with the oled
- Audio ins pass through to outs.
- Patch same lfo to CV in1, in2 (one at a time), got it on out1.
- Patch same lfo to CV in3, in4 (at the same time), got it on out2.
- Gatein passes through to gateout fine.

### json
There are no `led_sw_1` and `led_sw_2`.
Should add aliases for all knobs as ctrl. e.g. `ctrl1: knob1`.

## Daisy Petal

###  templates/oopsy_petal.maxpat
This example is totally borked. Needs to be reworked to test the petal effectively.

**Issues:**
- Switches need to use sw_pressed
- Leds are broken
- Pot6 is bipolar by default (I think)

### Pot Test
- Went through the knobs two at a time like this.
- 1-5 turned the noise up from 0 to full.

Pasted image 20220329150836
]

**Issues:**
- Pot 6 was quiet at noon and had sound to either side.
- Pot6 worked 0-1 when I manually set @max 1 @min 0. I figure it's defaulting to -1->1 then and the others are 0->1.


### Encoder Test
- press worked fine.
- encoder turn had to have @max and @min set. Not sure what this defaults to...
 
Pasted image 20220329152621

### Switch Test
- This worked for all 7 switches. They all needed sw_pressed.
- The toggles should probably default to sw_pressed.

Pasted image 20220330091335

- This didn't work with the one functioning led. User error?

Pasted image 20220330092615

### Footswitch Leds
- fs_1 works like this. The rest do not. Maybe they don't accept analog signals, just on or off?

Pasted image 20220329155348

### Encoder Leds
- This doesn't compile. The error comes about like this in the cpp 

```
 led_ring_1 = glue_out3[ size-1]; // device out

 hardware.led_driver.SetLed(, led_ring_1);

 hardware.led_driver.SetLed(, led_ring_1);

 hardware.led_driver.SetLed(, led_ring_1); // set out
 ```

### Expression
- Works!

Pasted image 20220330121108

## Daisy Patch

### templates/oopsy_patch.maxpat
- Gate IO: patched a gate into in1 and in2 one at a time. Both passed through to gate out.
- CV IO: Twiddled the knobs and scoped cvout1 and cvout2. Everything worked fine. The max min 10x made cv3 and cv4 a bit annoying to test.
- Encoder: I believe this is supposed to control the oled by default. Doesn't do that.

#### Audio
Using the template patch:

- In1 -> Out1 and In2 -> Out2 work fine.

**Issues: **
- In1/2 -> Out3 passes crazy noise. 
- In3 -> Out3 passes silence. 
- In2->Out4 passes crazy noise.
- In1/3/4->Out4 passes silence

## Daisy Patch Init

### templates/oopsy_patch_init.maxpat
- Toggle, cv2, cv5 go to cv_out2.
- cv1 and cv3 go to cv_out_1
- cv4,6,7,8 are untested
- Gate IO works fine, the switch works when in voltage mode(?) (toggle down)
- What's up with `s toggle`?

### CV 4,6,7,8 Test
Was able to test these by just swapping them into the previous template patch. `out 4 led` doesn't work despite the template saying it does.

### Knob test
Just swapped the `ctrl1` for `knob1`, etc. These work fine.

### ADC 9,10,11,12 Test
Works fine. I'd appreciate an alias as with cv. e.g. `adc10` for `adc_10`.

Pasted image 20220330104547

## SD Card
Tested on all platforms using `examples/sdcard-minimal.maxpat`.   
Working on patch, petal, field, pod, and patch.Init!

## Midi In
Midi seems to be coming in, I can see the `>` symbol in the oled when midi comes in. Wasn't able to convert midi -> freq in the gen~ patcher yet. 
This patch makes audio on the pc but not the daisy patch. Almost definitely user error here.

Pasted image 20220330145048

## Midi Out
Spent some time looking at this, couldn't really figure out a simple way to test it. Let me know if you've got a good patch to test this and / or midi in.

One simple thing could be passing midi in through to midi out but I don't have enough cables around to actually test that atm!

## Versio
We'll test this after this round of changes.

## # How To: Custom JSON with Oopsy
The section on Components is useful.
This should be fleshed out to indicate default @max and @min, special things like sw_pressed, etc.

We should update the section about it being a WIP once it's merged.

## Repo README
This hasn't been updated yet.
This should be modeled after the pd2dsy readme.

Explanation of @max and @min.
Explanation of the oled display.
Explanation of `poke leds` on field. We should get this working on the other boards if we haven't yet. It's really cool!
Any other special stuff like `s toggle` on the patch.Init(), or anything else I haven't found yet.

Explanation of interface types. (switch, encoder, rgb led, etc.)
Should list default @max and @min. Should list any special stuff like sw_pressed.

Tables per platform as it is with the pd2dsy readme.

All told there should be some cross-pollination between the custom json howto, the getting started with oopsy wiki, and the github readme. It's better to duplicate information than link all over the place like crazy.

## Code Review / Overall
Need to remove old json templates. `source/pod.json` vs `source/daisy.pod.json`

**Comment by beserge** [comment]
Abridged issues, refer to full test for details.

# Hardware
## Pod
I think these issues were already solved in pd2dsy some months ago.

- [ ] Led2 blue stuck on.
- [ ] Rgb colors don't sweep how the template/oopsy_pod.maxpat says they will. (template says green -> red, we do red -> blue)
- [ ] json has some fields that don't exist on the hw. (led3, sw3, cvout1, gatein).
- [ ] Template/oopsy_pod.json should be updated to fully and easily test the hardware. (Except maybe sdcard and midi).

## Field
- [ ] json has some extra fields. (led_sw_1, led_sw_2,)
- [ ] We should add aliases for _all_ knobs as ctrls. e.g. `ctrl1: knob1`

## Petal
- [ ] Example is borked. Switches need to use sw_pressed!
- [ ] led_fs_2,3,4 are stuck on, led_fs_1 works!
- [ ] None of the ring leds can be used, there's a compiler issue. There's some more info in the full test writeup.
- [ ] Pot6 seems to default to bipolar where the others are unipolar.
- [ ] Encoder had to have `@max` and `@min` manually set, I don't recall having to do that on the pod.

## Patch
- [ ] Audio is broken. IO 3 and 4 have issues. More info in full test writeup.

## Patch Init 
- [ ] Template claims `out 4 led` works. It does not.
- [ ] Should add aliases for all of the adcs with underscores. e.g. `adc10: adc_10`


## Midi IO
This sort of worked. It would be helpful to me, and probably users if we had a nice midiout and midiin example that works on all platforms, similar to the sdcard example. The current midi example doesn't really show how to use midi in gen.

# Documentation
Needs some love. Refer to the full test writeup for more info.

# Overall code stuf
- [ ] Need to rm old json templates. e.g. `source/daisy.pod.json`

**Comment by CorvusPrudens** [comment]
## MIDI Out
I've now tested MIDI output with simple note on / off messages using the following configuration on the Patch and Field (with an appropriate trigger input for each platform):
Screen Shot 2022-04-07 at 1 37 17 PM

MIDI output worked as expected using the right range for notes and the expected velocity of 127. 

## Field LEDs and pads
There was a lurking issue present with the order of pads and LEDs on the field (which had been corrected already in pd2dsy). This was easy to test, since hooking up a metro to an LED (instead of the corresponding pad) would not illuminate the expected pad. Essentially, the pads and LEDs were jumbled up in a complementary way to make the Field template appear to behave correctly.

This has now been resolved.

**Comment by CorvusPrudens** [comment]
While the code was in place to resolve bipolar input issues, the patch.Init() JSON omitted the necessary range field and the patcher omitted the `@min -1` attribute. With the following simple test, it was very easy to verify the problem:
Screen Shot 2022-04-18 at 2 35 01 PM
Before the most recent two commits, the above configuration would not illuminate the LED. Once the changes were made, the LED lit up when I provided an input below 0 volts as expected.

The template patcher has been corrected and now includes `@min -1` on all inputs that expect a bipolar input.

**Comment by CorvusPrudens** [comment]
This was superseded by #71, which will be merged into main at a later date.

**Pull request closed without merging**
